import { CharacterClass, Dragon, Pet, PlayerState, ShopItem, VipTier } from '../types/game';

export const CHARACTER_CLASSES: CharacterClass[] = [
  {
    id: 'dragon-knight',
    name: 'Dragon Knight',
    title: 'Sword of the Flame',
    description: 'A fearless warrior who wields the power of dragons. High attack and resilient defense.',
    maxHp: 550,
    maxMp: 120,
    attack: 75,
    defense: 40,
    speed: 60,
    color: '#dc2626',
    accentColor: '#fca5a5',
    skills: [
      { id: 'iron-slash', name: 'Iron Slash', damage: 30, mpCost: 0, type: 'physical', description: 'A swift blade strike.', cooldown: 0, currentCooldown: 0, icon: 'Sword' },
      { id: 'dragon-strike', name: 'Dragon Strike', damage: 65, mpCost: 20, type: 'physical', description: 'Channel dragon power into a devastating blow.', cooldown: 1, currentCooldown: 0, icon: 'Zap' },
      { id: 'flame-burst', name: 'Flame Burst', damage: 90, mpCost: 35, type: 'magic', description: 'Release dragon fire upon your foe.', cooldown: 2, currentCooldown: 0, icon: 'Flame' },
      { id: 'berserker-rage', name: 'Berserker Rage', damage: 140, mpCost: 55, type: 'physical', description: 'Enter a frenzy for a catastrophic strike.', cooldown: 3, currentCooldown: 0, icon: 'Skull' },
    ],
  },
  {
    id: 'fire-mage',
    name: 'Fire Mage',
    title: 'Archmage of Cinders',
    description: 'A master of forbidden fire magic. Devastating magical power but fragile constitution.',
    maxHp: 380,
    maxMp: 240,
    attack: 45,
    defense: 20,
    speed: 75,
    color: '#ea580c',
    accentColor: '#fdba74',
    skills: [
      { id: 'fire-bolt', name: 'Fire Bolt', damage: 40, mpCost: 5, type: 'magic', description: 'Hurl a bolt of fire.', cooldown: 0, currentCooldown: 0, icon: 'Zap' },
      { id: 'fireball', name: 'Fireball', damage: 80, mpCost: 25, type: 'magic', description: 'An explosive ball of flame.', cooldown: 1, currentCooldown: 0, icon: 'Circle' },
      { id: 'meteor', name: 'Meteor', damage: 120, mpCost: 45, type: 'magic', description: 'Call down a meteor from the sky.', cooldown: 2, currentCooldown: 0, icon: 'Flame' },
      { id: 'phoenix-flame', name: 'Phoenix Flame', damage: 170, mpCost: 70, type: 'magic', description: 'Unleash the eternal flame of the phoenix.', cooldown: 3, currentCooldown: 0, icon: 'Star' },
    ],
  },
  {
    id: 'shadow-archer',
    name: 'Shadow Archer',
    title: 'Phantom of Darkness',
    description: 'A swift hunter who strikes from the shadows. Exceptional speed and precision.',
    maxHp: 440,
    maxMp: 160,
    attack: 65,
    defense: 25,
    speed: 95,
    color: '#0891b2',
    accentColor: '#67e8f9',
    skills: [
      { id: 'quick-shot', name: 'Quick Shot', damage: 28, mpCost: 0, type: 'physical', description: 'A rapid precise arrow.', cooldown: 0, currentCooldown: 0, icon: 'Target' },
      { id: 'arrow-rain', name: 'Arrow Rain', damage: 55, mpCost: 20, type: 'physical', description: 'Release a volley of arrows.', cooldown: 1, currentCooldown: 0, icon: 'Zap' },
      { id: 'shadow-strike', name: 'Shadow Strike', damage: 95, mpCost: 35, type: 'physical', description: 'Strike from the blind side.', cooldown: 2, currentCooldown: 0, icon: 'Eye' },
      { id: 'death-mark', name: 'Death Mark', damage: 150, mpCost: 55, type: 'magic', description: 'Mark the target for death. Ignores defense.', cooldown: 3, currentCooldown: 0, icon: 'Skull' },
    ],
  },
  {
    id: 'holy-paladin',
    name: 'Holy Paladin',
    title: 'Champion of the Sacred Flame',
    description: 'A divine warrior blessed by the gods. Balanced stats with powerful healing abilities.',
    maxHp: 500,
    maxMp: 180,
    attack: 60,
    defense: 45,
    speed: 55,
    color: '#d97706',
    accentColor: '#fde68a',
    skills: [
      { id: 'holy-strike', name: 'Holy Strike', damage: 25, mpCost: 5, type: 'physical', description: 'A strike imbued with holy energy.', cooldown: 0, currentCooldown: 0, icon: 'Sword' },
      { id: 'sacred-heal', name: 'Sacred Heal', damage: -80, mpCost: 25, type: 'heal', description: 'Channel divine light to restore health.', cooldown: 1, currentCooldown: 0, icon: 'Heart' },
      { id: 'divine-smite', name: 'Divine Smite', damage: 85, mpCost: 35, type: 'magic', description: 'Smite foes with divine wrath.', cooldown: 2, currentCooldown: 0, icon: 'Star' },
      { id: 'judgment', name: 'Judgment', damage: 130, mpCost: 55, type: 'magic', description: 'Call upon the gods to deliver final judgment.', cooldown: 3, currentCooldown: 0, icon: 'Shield' },
    ],
  },
  {
    id: 'frost-sorcerer',
    name: 'Frost Sorcerer',
    title: 'Master of Winter\'s Wrath',
    description: 'A cryomancer wielding absolute control over ice and winter. Powerful magic with moderate defenses.',
    maxHp: 420,
    maxMp: 260,
    attack: 50,
    defense: 28,
    speed: 70,
    color: '#0ea5e9',
    accentColor: '#bae6fd',
    skills: [
      { id: 'ice-lance', name: 'Ice Lance', damage: 35, mpCost: 8, type: 'magic', description: 'Launches a shard of crystalline ice.', cooldown: 0, currentCooldown: 0, icon: 'Zap' },
      { id: 'frost-nova', name: 'Frost Nova', damage: 75, mpCost: 22, type: 'magic', description: 'Explodes in a burst of freezing energy.', cooldown: 1, currentCooldown: 0, icon: 'Circle' },
      { id: 'blizzard', name: 'Blizzard Storm', damage: 110, mpCost: 42, type: 'magic', description: 'Summons a devastating blizzard.', cooldown: 2, currentCooldown: 0, icon: 'Flame' },
      { id: 'absolute-zero', name: 'Absolute Zero', damage: 165, mpCost: 68, type: 'magic', description: 'Freezes the target in time itself.', cooldown: 3, currentCooldown: 0, icon: 'Star' },
    ],
  },
  {
    id: 'demon-slayer',
    name: 'Demon Slayer',
    title: 'Scourge of Darkness',
    description: 'A ruthless warrior who hunts creatures of darkness. High damage output with moderate HP.',
    maxHp: 480,
    maxMp: 140,
    attack: 78,
    defense: 32,
    speed: 72,
    color: '#a855f7',
    accentColor: '#e9d5ff',
    skills: [
      { id: 'demon-slash', name: 'Demon Slash', damage: 32, mpCost: 3, type: 'physical', description: 'Cleaves with dark-infused steel.', cooldown: 0, currentCooldown: 0, icon: 'Sword' },
      { id: 'void-pierce', name: 'Void Pierce', damage: 72, mpCost: 18, type: 'physical', description: 'Pierces through void and matter alike.', cooldown: 1, currentCooldown: 0, icon: 'Target' },
      { id: 'shadow-execution', name: 'Shadow Execution', damage: 105, mpCost: 32, type: 'physical', description: 'A finishing move that cuts through shadows.', cooldown: 2, currentCooldown: 0, icon: 'Skull' },
      { id: 'apocalypse-blade', name: 'Apocalypse Blade', damage: 155, mpCost: 52, type: 'magic', description: 'Unleashes a world-ending slash of pure darkness.', cooldown: 3, currentCooldown: 0, icon: 'Skull' },
    ],
  },
  {
    id: 'nature-druid',
    name: 'Nature Druid',
    title: 'Keeper of the Ancient Woods',
    description: 'A guardian of nature with balanced offense and defense, and the ability to heal and control nature.',
    maxHp: 520,
    maxMp: 200,
    attack: 58,
    defense: 38,
    speed: 65,
    color: '#16a34a',
    accentColor: '#86efac',
    skills: [
      { id: 'vine-strike', name: 'Vine Strike', damage: 26, mpCost: 6, type: 'physical', description: 'Strikes with animated vines.', cooldown: 0, currentCooldown: 0, icon: 'Circle' },
      { id: 'nature-heal', name: 'Nature\'s Blessing', damage: -90, mpCost: 28, type: 'heal', description: 'Channels nature\'s restorative power.', cooldown: 1, currentCooldown: 0, icon: 'Heart' },
      { id: 'entangle', name: 'Entangle', damage: 68, mpCost: 30, type: 'magic', description: 'Binds the enemy with thorny vines.', cooldown: 2, currentCooldown: 0, icon: 'Shield' },
      { id: 'forest-wrath', name: 'Forest\'s Wrath', damage: 135, mpCost: 58, type: 'magic', description: 'Summons the ancient anger of the forest.', cooldown: 3, currentCooldown: 0, icon: 'Star' },
    ],
  },
  {
    id: 'legendary-warrior',
    name: 'Legendary Warrior',
    title: 'The Immortal Champion',
    description: 'A legendary warrior of immense power. Highest HP and balanced combat abilities.',
    maxHp: 620,
    maxMp: 150,
    attack: 72,
    defense: 50,
    speed: 58,
    color: '#eab308',
    accentColor: '#fef08a',
    skills: [
      { id: 'warrior-strike', name: 'Warrior Strike', damage: 28, mpCost: 2, type: 'physical', description: 'A powerful blade strike.', cooldown: 0, currentCooldown: 0, icon: 'Sword' },
      { id: 'shield-bash', name: 'Shield Bash', damage: 48, mpCost: 12, type: 'physical', description: 'Bash with your shield to stun.', cooldown: 1, currentCooldown: 0, icon: 'Shield' },
      { id: 'whirlwind', name: 'Whirlwind Attack', damage: 98, mpCost: 36, type: 'physical', description: 'Spins to hit all enemies in range.', cooldown: 2, currentCooldown: 0, icon: 'Circle' },
      { id: 'legendary-strike', name: 'Legendary Strike', damage: 150, mpCost: 54, type: 'physical', description: 'A strike that echoes through legend itself.', cooldown: 3, currentCooldown: 0, icon: 'Star' },
    ],
  },
];

export const DRAGONS: Dragon[] = [
  {
    id: 'fire-drake',
    name: 'Ignathar',
    title: 'The Fire Drake',
    hp: 350,
    maxHp: 350,
    attack: 40,
    defense: 18,
    level: 5,
    color: '#dc2626',
    description: 'A young but ferocious fire dragon that guards the Scorched Highlands.',
    rewardExp: 200,
    rewardGold: 150,
    rewardDiamonds: 20,
    abilities: [
      { name: 'Claw Swipe', damage: 35, description: 'Rakes with razor-sharp claws.', type: 'physical' },
      { name: 'Flame Breath', damage: 55, description: 'Exhales a torrent of scorching flames.', type: 'fire' },
      { name: 'Tail Slam', damage: 45, description: 'Crashes its massive tail down.', type: 'physical' },
    ],
  },
  {
    id: 'frost-wyrm',
    name: 'Glaciveth',
    title: 'The Frost Wyrm',
    hp: 500,
    maxHp: 500,
    attack: 55,
    defense: 28,
    level: 12,
    color: '#0891b2',
    description: 'An ancient serpent of ice that has slumbered beneath the Frozen Peaks for centuries.',
    rewardExp: 400,
    rewardGold: 300,
    rewardDiamonds: 40,
    abilities: [
      { name: 'Ice Bite', damage: 50, description: 'Bites with fangs coated in frost.', type: 'ice' },
      { name: 'Blizzard Breath', damage: 70, description: 'Unleashes a devastating blizzard.', type: 'ice' },
      { name: 'Frost Crush', damage: 60, description: 'Crushes with ice-hardened scales.', type: 'physical' },
    ],
  },
  {
    id: 'storm-serpent',
    name: 'Drakonor',
    title: 'The Storm Serpent',
    hp: 620,
    maxHp: 620,
    attack: 62,
    defense: 30,
    level: 18,
    color: '#16a34a',
    description: 'A colossal serpent wreathed in living lightning. Its scales crackle with centuries of stored storm energy.',
    rewardExp: 550,
    rewardGold: 420,
    rewardDiamonds: 60,
    abilities: [
      { name: 'Thunder Fang', damage: 62, description: 'Bites with electrified fangs.', type: 'physical' },
      { name: 'Tempest Breath', damage: 82, description: 'Exhales a torrent of lightning and wind.', type: 'dark' },
      { name: 'Lightning Coil', damage: 72, description: 'Wraps the enemy in crackling lightning coils.', type: 'dark' },
    ],
  },
  {
    id: 'molten-colossus',
    name: 'Infernus',
    title: 'The Molten Colossus',
    hp: 720,
    maxHp: 720,
    attack: 70,
    defense: 36,
    level: 22,
    color: '#ea580c',
    description: 'A mountain of living magma and obsidian scales. Every breath scorches the ground to glass.',
    rewardExp: 680,
    rewardGold: 540,
    rewardDiamonds: 80,
    abilities: [
      { name: 'Magma Crush', damage: 68, description: 'Slams down a molten fist of rock.', type: 'fire' },
      { name: 'Volcanic Breath', damage: 92, description: 'Unleashes a river of superheated lava.', type: 'fire' },
      { name: 'Pyroclast', damage: 80, description: 'Launches a barrage of explosive magma balls.', type: 'fire' },
    ],
  },
  {
    id: 'ancient-dragon',
    name: 'Malachar',
    title: 'The Ancient One',
    hp: 900,
    maxHp: 900,
    attack: 82,
    defense: 45,
    level: 30,
    color: '#7c3aed',
    description: 'The oldest and most powerful dragon in existence. Its very breath corrupts reality.',
    rewardExp: 900,
    rewardGold: 700,
    rewardDiamonds: 150,
    abilities: [
      { name: 'Void Claw', damage: 78, description: 'Strikes with claws that tear at existence.', type: 'dark' },
      { name: 'Shadow Breath', damage: 105, description: 'Breathes dark energy that devours light.', type: 'dark' },
      { name: 'Ancient Wrath', damage: 130, description: 'Channels eons of rage into a single cataclysmic blow.', type: 'dark' },
    ],
  },
];

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'minor-hp-potion',
    name: 'Dragon Blood Draught',
    description: 'A vial of potent dragon blood that rapidly seals wounds.',
    effectLabel: 'Restore 150 HP',
    price: 60,
    rarity: 'common',
    type: 'consumable',
    icon: '🩸',
    maxPurchases: -1,
  },
  {
    id: 'major-hp-potion',
    name: 'Elixir of Vitality',
    description: 'A rare elixir brewed from ancient herbs and dragon essence.',
    effectLabel: 'Restore 350 HP',
    price: 140,
    rarity: 'rare',
    type: 'consumable',
    icon: '💊',
    maxPurchases: -1,
  },
  {
    id: 'mana-potion',
    name: 'Arcane Essence',
    description: 'Crystallized magical energy dissolved in enchanted water.',
    effectLabel: 'Restore 100 MP',
    price: 70,
    rarity: 'common',
    type: 'consumable',
    icon: '💧',
    maxPurchases: -1,
  },
  {
    id: 'full-restore',
    name: 'Grand Elixir',
    description: 'The pinnacle of alchemical achievement. Fully restores the body.',
    effectLabel: 'Full HP & MP Restore',
    price: 280,
    rarity: 'epic',
    type: 'consumable',
    icon: '✨',
    maxPurchases: 2,
  },
  {
    id: 'attack-rune',
    name: 'Warbrand Rune',
    description: 'A rune carved from dragon bone. Enhances your next battle\'s offensive power.',
    effectLabel: '+20 ATK for next battle',
    price: 120,
    rarity: 'rare',
    type: 'buff',
    icon: '⚔',
    maxPurchases: 3,
  },
  {
    id: 'defense-rune',
    name: 'Ironhide Rune',
    description: 'Ancient protective magic sealed within draconic scales.',
    effectLabel: '+15 DEF for next battle',
    price: 100,
    rarity: 'rare',
    type: 'buff',
    icon: '🛡',
    maxPurchases: 3,
  },
  {
    id: 'speed-rune',
    name: 'Swiftclaw Rune',
    description: 'Infused with the essence of the fastest dragon. Move like the wind.',
    effectLabel: '+20 SPD for next battle',
    price: 110,
    rarity: 'rare',
    type: 'buff',
    icon: '💨',
    maxPurchases: 3,
  },
  {
    id: 'phoenix-feather',
    name: 'Phoenix Feather',
    description: 'A feather from the immortal phoenix. It burns with undying life force.',
    effectLabel: 'Revive with 50% HP once',
    price: 380,
    rarity: 'epic',
    type: 'special',
    icon: '🪶',
    maxPurchases: 1,
  },
  {
    id: 'cooldown-reset',
    name: 'Void Hourglass',
    description: 'A cursed artifact that bends time itself. All cooldowns reset at battle start.',
    effectLabel: 'Reset all cooldowns at battle start',
    price: 420,
    rarity: 'epic',
    type: 'special',
    icon: '⏳',
    maxPurchases: 1,
  },
  {
    id: 'vip-dragon-heart',
    name: 'Dragon Heart Crystal',
    description: 'The crystallized heart of an elder dragon, pulsing with raw destructive power.',
    effectLabel: '+40 ATK permanently',
    price: 650,
    rarity: 'vip',
    type: 'permanent',
    icon: '💎',
    maxPurchases: 1,
  },
  {
    id: 'vip-dragon-scale',
    name: 'Ancientscale Armor',
    description: 'Forged from the impenetrable scales of the most ancient dragon.',
    effectLabel: '+25 DEF permanently',
    price: 520,
    rarity: 'vip',
    type: 'permanent',
    icon: '🔮',
    maxPurchases: 1,
  },
  {
    id: 'vip-dragon-soul',
    name: "Dragon Soul Vessel",
    description: "A vessel containing the essence of a slain dragon. Permanently expands your life force.",
    effectLabel: '+200 Max HP permanently',
    price: 580,
    rarity: 'vip',
    type: 'permanent',
    icon: '👑',
    maxPurchases: 1,
  },
  {
    id: 'iron-sword',
    name: 'Iron Sword',
    description: 'A well-forged blade of iron. Reliable and effective.',
    effectLabel: '+8 ATK permanently',
    price: 120,
    rarity: 'common',
    type: 'permanent',
    icon: '⚔',
    maxPurchases: 1,
  },
  {
    id: 'steel-mace',
    name: 'Tempered Steel Mace',
    description: 'A crushing weapon of steel. Heavier but more damaging than swords.',
    effectLabel: '+12 ATK permanently',
    price: 180,
    rarity: 'common',
    type: 'permanent',
    icon: '🔨',
    maxPurchases: 1,
  },
  {
    id: 'crystal-bow',
    name: 'Crystal Bow',
    description: 'A bow crafted from pure crystal. Allows for faster, deadlier shots.',
    effectLabel: '+10 ATK, +5 SPD permanently',
    price: 200,
    rarity: 'rare',
    type: 'permanent',
    icon: '🏹',
    maxPurchases: 1,
  },
  {
    id: 'enchanted-staff',
    name: 'Enchanted Mage Staff',
    description: 'A staff radiating magical energy. Amplifies spell power.',
    effectLabel: '+15 ATK permanently',
    price: 240,
    rarity: 'rare',
    type: 'permanent',
    icon: '🎯',
    maxPurchases: 1,
  },
  {
    id: 'obsidian-blade',
    name: 'Obsidian Blade',
    description: 'A blade forged from volcanic obsidian. Cuts through armor like paper.',
    effectLabel: '+20 ATK permanently',
    price: 350,
    rarity: 'rare',
    type: 'permanent',
    icon: '⚔',
    maxPurchases: 1,
  },
  {
    id: 'ancient-halberd',
    name: 'Ancient Halberd',
    description: 'A legendary weapon from a forgotten age. Combines bladed and crushing power.',
    effectLabel: '+28 ATK permanently',
    price: 480,
    rarity: 'epic',
    type: 'permanent',
    icon: '🔱',
    maxPurchases: 1,
  },
  {
    id: 'excalibur-replica',
    name: 'Excalibur\'s Echo',
    description: 'A legendary replica of the king\'s sword. Radiates divine power.',
    effectLabel: '+35 ATK, +10 DEF permanently',
    price: 620,
    rarity: 'epic',
    type: 'permanent',
    icon: '⚔',
    maxPurchases: 1,
  },
  {
    id: 'inferno-wand',
    name: 'Inferno Wand',
    description: 'A wand crackling with fire magic. Increases the power of fire spells.',
    effectLabel: '+25 ATK permanently',
    price: 520,
    rarity: 'epic',
    type: 'permanent',
    icon: '🔥',
    maxPurchases: 1,
  },
  {
    id: 'dragonslay-sword',
    name: 'Dragonslay Sword',
    description: 'A legendary blade specifically forged to slay dragons. Nearly unbreakable.',
    effectLabel: '+42 ATK permanently',
    price: 750,
    rarity: 'vip',
    type: 'permanent',
    icon: '⚔',
    maxPurchases: 1,
  },
  {
    id: 'ethereal-bow',
    name: 'Ethereal Bow',
    description: 'A bow that fires arrows from the spirit realm. Arrows never miss.',
    effectLabel: '+40 ATK, +15 SPD permanently',
    price: 700,
    rarity: 'vip',
    type: 'permanent',
    icon: '🏹',
    maxPurchases: 1,
  },
  {
    id: 'divine-glaive',
    name: 'Divine Glaive',
    description: 'Blessed by the gods themselves. An artifact of immense power.',
    effectLabel: '+50 ATK, +20 DEF permanently',
    price: 850,
    rarity: 'vip',
    type: 'permanent',
    icon: '🔱',
    maxPurchases: 1,
  },
];

export function calculateDamage(
  attackerAttack: number,
  skillDamage: number,
  defenderDefense: number,
  ignoreDefense = false
): number {
  const base = skillDamage + attackerAttack * 0.5;
  const reduced = ignoreDefense ? base : Math.max(5, base - defenderDefense * 0.4);
  const variance = 0.9 + Math.random() * 0.2;
  const isCrit = Math.random() < 0.15;
  const finalDamage = Math.floor(reduced * variance * (isCrit ? 1.8 : 1));
  return finalDamage;
}

export function calculateEnemyDamage(enemyAttack: number, abilityDamage: number, playerDefense: number): number {
  const base = abilityDamage + enemyAttack * 0.4;
  const reduced = Math.max(3, base - playerDefense * 0.35);
  const variance = 0.85 + Math.random() * 0.3;
  return Math.floor(reduced * variance);
}

export const PETS: Pet[] = [
  {
    id: 'ember-fox',
    name: 'Ember Fox',
    title: 'Spirit of the Flame',
    description: 'A fiery fox spirit born from volcanic ash. Its tails radiate scorching heat.',
    element: 'fire',
    rarity: 'rare',
    color: '#ef4444',
    accentColor: '#fca5a5',
    bonusAtk: 15,
    bonusDef: 5,
    bonusHp: 80,
    bonusSpeed: 10,
    battleSkillName: 'Inferno Tail',
    battleSkillDamage: 45,
    battleSkillDescription: 'Whips the enemy with a tail of pure fire.',
    unlockCost: 300,
    unlockCostType: 'gold',
  },
  {
    id: 'frost-sprite',
    name: 'Frost Sprite',
    title: 'Child of the Frozen Peaks',
    description: 'A crystalline spirit forged from glacier ice. It chills foes to the bone.',
    element: 'ice',
    rarity: 'rare',
    color: '#38bdf8',
    accentColor: '#bae6fd',
    bonusAtk: 10,
    bonusDef: 15,
    bonusHp: 100,
    bonusSpeed: 8,
    battleSkillName: 'Glacial Shard',
    battleSkillDamage: 40,
    battleSkillDescription: 'Launches a razor-sharp shard of enchanted ice.',
    unlockCost: 350,
    unlockCostType: 'gold',
  },
  {
    id: 'thunder-hawk',
    name: 'Thunder Hawk',
    title: 'Harbinger of Storms',
    description: 'A majestic hawk whose feathers crackle with endless lightning. Fastest of all pets.',
    element: 'storm',
    rarity: 'epic',
    color: '#facc15',
    accentColor: '#fef08a',
    bonusAtk: 20,
    bonusDef: 8,
    bonusHp: 120,
    bonusSpeed: 25,
    battleSkillName: 'Thunderstrike',
    battleSkillDamage: 70,
    battleSkillDescription: 'Dives at lightning speed, striking with electrified talons.',
    unlockCost: 80,
    unlockCostType: 'diamonds',
  },
  {
    id: 'shadow-wolf',
    name: 'Shadow Wolf',
    title: 'Phantom of Darkness',
    description: 'A spectral wolf that phases in and out of reality. Strikes from the void itself.',
    element: 'shadow',
    rarity: 'epic',
    color: '#a78bfa',
    accentColor: '#ddd6fe',
    bonusAtk: 30,
    bonusDef: 10,
    bonusHp: 90,
    bonusSpeed: 18,
    battleSkillName: 'Void Fang',
    battleSkillDamage: 85,
    battleSkillDescription: 'Bites with fangs that tear through the fabric of existence.',
    unlockCost: 120,
    unlockCostType: 'diamonds',
  },
  {
    id: 'sacred-unicorn',
    name: 'Sacred Unicorn',
    title: 'Divine Guardian',
    description: 'A legendary unicorn blessed by the gods themselves. Its horn radiates holy power.',
    element: 'holy',
    rarity: 'legendary',
    color: '#f0abfc',
    accentColor: '#fae8ff',
    bonusAtk: 25,
    bonusDef: 25,
    bonusHp: 200,
    bonusSpeed: 15,
    battleSkillName: 'Holy Lance',
    battleSkillDamage: 100,
    battleSkillDescription: 'Charges forward with a radiant horn imbued with divine wrath.',
    unlockCost: 250,
    unlockCostType: 'diamonds',
  },
  {
    id: 'dragon-hatchling',
    name: 'Dragon Hatchling',
    title: 'Child of the Ancient',
    description: 'A hatchling born from the egg of Malachar himself. Already radiates immense draconic power.',
    element: 'dragon',
    rarity: 'legendary',
    color: '#7c3aed',
    accentColor: '#c4b5fd',
    bonusAtk: 45,
    bonusDef: 20,
    bonusHp: 250,
    bonusSpeed: 20,
    battleSkillName: 'Ancient Breath',
    battleSkillDamage: 130,
    battleSkillDescription: 'Breathes a torrent of ancient dragon fire that scorches reality.',
    unlockCost: 400,
    unlockCostType: 'diamonds',
  },
];

export const VIP_TIERS: VipTier[] = [
  {
    level: 1,
    title: 'Bronze Slayer',
    diamondsRequired: 0,
    color: '#cd7f32',
    benefits: ['Access to VIP Shop', '+5% Gold Drops'],
    bonusAtk: 5,
    bonusDef: 3,
    bonusHpPercent: 5,
    goldMultiplier: 1.05,
    expMultiplier: 1.0,
  },
  {
    level: 2,
    title: 'Silver Champion',
    diamondsRequired: 200,
    color: '#94a3b8',
    benefits: ['+10% Gold Drops', '+5% EXP Gain', 'Silver aura'],
    bonusAtk: 10,
    bonusDef: 6,
    bonusHpPercent: 8,
    goldMultiplier: 1.1,
    expMultiplier: 1.05,
  },
  {
    level: 3,
    title: 'Gold Dragonslayer',
    diamondsRequired: 500,
    color: '#f59e0b',
    benefits: ['+20% Gold Drops', '+10% EXP Gain', 'Gold aura'],
    bonusAtk: 18,
    bonusDef: 10,
    bonusHpPercent: 12,
    goldMultiplier: 1.2,
    expMultiplier: 1.1,
  },
  {
    level: 4,
    title: 'Platinum Warlord',
    diamondsRequired: 1000,
    color: '#e2e8f0',
    benefits: ['+30% Gold Drops', '+20% EXP Gain', 'Platinum aura'],
    bonusAtk: 28,
    bonusDef: 16,
    bonusHpPercent: 18,
    goldMultiplier: 1.3,
    expMultiplier: 1.2,
  },
  {
    level: 5,
    title: 'Diamond Sovereign',
    diamondsRequired: 2000,
    color: '#67e8f9',
    benefits: ['+40% Gold Drops', '+30% EXP Gain', 'Diamond aura'],
    bonusAtk: 40,
    bonusDef: 22,
    bonusHpPercent: 25,
    goldMultiplier: 1.4,
    expMultiplier: 1.3,
  },
  {
    level: 6,
    title: 'Dragon Lord',
    diamondsRequired: 4000,
    color: '#f97316',
    benefits: ['+55% Gold Drops', '+45% EXP Gain', 'Blazing aura'],
    bonusAtk: 55,
    bonusDef: 30,
    bonusHpPercent: 35,
    goldMultiplier: 1.55,
    expMultiplier: 1.45,
  },
  {
    level: 7,
    title: 'Mythic Conqueror',
    diamondsRequired: 8000,
    color: '#dc2626',
    benefits: ['+70% Gold Drops', '+60% EXP Gain', 'Infernal aura'],
    bonusAtk: 72,
    bonusDef: 40,
    bonusHpPercent: 50,
    goldMultiplier: 1.7,
    expMultiplier: 1.6,
  },
  {
    level: 8,
    title: 'Eternal Dragon Emperor',
    diamondsRequired: 15000,
    color: '#f59e0b',
    benefits: ['+100% Gold Drops', '+100% EXP Gain', 'Legendary divine aura', 'Exclusive Emperor title'],
    bonusAtk: 100,
    bonusDef: 55,
    bonusHpPercent: 70,
    goldMultiplier: 2.0,
    expMultiplier: 2.0,
  },
];

export function getVipTier(vipLevel: number): VipTier {
  return VIP_TIERS[Math.max(0, Math.min(vipLevel - 1, VIP_TIERS.length - 1))];
}

export function getPetById(id: string | null): Pet | null {
  if (!id) return null;
  return PETS.find(p => p.id === id) ?? null;
}

export function calculateBR(player: PlayerState): number {
  const hpScore = Math.floor(player.maxHp * 0.8);
  const atkScore = player.attack * 10;
  const defScore = player.defense * 6;
  const spdScore = Math.floor(player.speed * 4);
  const expScore = Math.floor((player.exp ?? 0) * 0.5);
  const goldScore = Math.floor((player.gold ?? 0) * 0.3);
  const levelScore = player.level * 500;
  const featherScore = player.hasPhoenixFeather ? 800 : 0;
  const resetScore = player.hasCooldownReset ? 600 : 0;
  const buffScore = (player.buffs?.attack ?? 0) * 15 + (player.buffs?.defense ?? 0) * 10 + (player.buffs?.speed ?? 0) * 8;
  const vipScore = (player.vipLevel ?? 0) * 1200;
  const activePet = getPetById(player.activePetId ?? null);
  const petScore = activePet ? (activePet.bonusAtk * 12 + activePet.bonusDef * 8 + activePet.bonusHp * 0.6 + activePet.bonusSpeed * 6 + activePet.battleSkillDamage * 4) : 0;
  return hpScore + atkScore + defScore + spdScore + expScore + goldScore + levelScore + featherScore + resetScore + buffScore + vipScore + petScore;
}

export function formatBR(br: number): string {
  if (br >= 10000) return `${(br / 1000).toFixed(1)}k`;
  return br.toLocaleString();
}
